name: Create and Publish Release
permissions:
  contents: write
on:
  push:
    tags:
      - 'v*'  # Runs when a tag starting with 'v' is pushed (e.g., v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP Archive
        run: |
          zip -r WolfTweaks.zip . -x ".git/*"

      - name: Upload ZIP as Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: WolfTweaks.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
